### ISSUE TITLE
Why you don' t like hybrid apps?

### ISSUE THREAD

**Issue by radek-anuszewski** [rishabhp/ama#20]
Hi! In [Strategy for your new startup #13](https://github.com/rishabhp/ama/issues/13) you wrote that you are not fan of a hybrid apps. Would you like to tell why? What are, in your opinion, pros and contras to you hybrid instead of native apps?

**Comment by rishabhp** [comment]
Performance, API access, Design guideline specific things. Although it's getting better and better with time. We'll reach there one day.

There are certain tools like Xamarin available that does a beautiful job but at the end of the day instead of learning new APIs of such tools, why not learn the native APIs itself. I learnt a lot about OS in general and various other threading, looping, etc. concepts while coding Android. I'm sure there are other exciting new things that can be learnt with Swift/ObjC too.
