### ISSUE TITLE
Blogging for a complete fresher

### ISSUE THREAD

**Issue by srinivasdamam** [rishabhp/ama#26]
Hi, I would like to know which hosting are you using for codetheory. How much you are spending on your blog annually. I'm working as a web developer since one month and is it good for me to start blogging as I'm a complete fresher. I would like hear you opinion on blogging. Thank you. Have a nice day.

**Comment by rishabhp** [comment]
Hosting is from [Linode](https://www.linode.com/). I have the $20/month server which equates to $240 per annum cost.

Blogging is great! Not only do you help others with the information posted but also sort of create a future reference for yourself. If your blog drives a lot of traffic due to the quality of articles then you can land up umpteen freelance contracts and even full time job offers for yourself. Oh! you can also make money via ads.
